name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: [self-hosted, ${{ matrix.os }}] # 셀프 호스트 러너를 사용하도록 변경
    strategy:
      matrix:
        os: [windows, macos, linux] # 러너 라벨에 맞게 OS 이름 변경

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            npm run build:win
          elif [ "$RUNNER_OS" == "macOS" ]; then
            npm run build:osx
          elif [ "$RUNNER_OS" == "Linux" ]; then
            npm run build:linux
          fi
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest # 릴리즈 잡은 GitHub 호스팅 러너 사용
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}